testEpoll:
	gcc -o testEpoll ../EventTree.c testEpoll.c ../CPthreadPool.c -pthread ../linkTab.c ../Queue.c
testPool:
	gcc -o testPool testPool.c ../CPthreadPool.c -pthread ../linkTab.c ../Queue.c
testSocket:
		gcc -o testSocket testSocket.c ../SocketConnect.c ../AcceptConnectTask.c ../CPthreadPool.c ../EventTree.c ../HttpTask.c -pthread ../linkTab.c ../Queue.c
